Feature/UI optimize
LISTENAI/cskburn-desktop pull request #1
Opened 2024-12-25 08:52 UTC by seasonyuu

主要修改内容：
1. 监听文件变化，对文件大小变化、修改时间变化、删除做出界面对应展示；
2. 表格 item 新增固定显示的修改日期项、定位文件按钮。

2024-12-25 08:53 UTC, seasonyuu commented
附图
![image](https://github.com/user-attachments/assets/e8fcf94d-8d57-4fde-8d1d-479e4ce9abe6)
![image](https://github.com/user-attachments/assets/2d205b5a-4ba1-490a-a52f-311a8a0b4a98)

2024-12-25 08:58 UTC, xingrz requested changes

2024-12-25 08:58 UTC, xingrz commented on src/components/common/FormatTime.vue
> +const formatter = Intl.DateTimeFormat('zh-CN', {
不要自己造轮子，看看naive-ui有没有自带了dayjs或者什么东西。没有就弄个luxon吧

2024-12-25 08:58 UTC, xingrz commented on src-tauri/Cargo.toml
>  tauri = { version = "2.0.0-beta", features = [] }
不如顺便帮我升个2.0正式版？

2024-12-25 08:58 UTC, xingrz commented on src/components/common/FormatTime.vue
> +<style lang="scss" module>
多余的

2024-12-26 08:07 UTC, seasonyuu commented on src/components/common/FormatTime.vue
> +const formatter = Intl.DateTimeFormat('zh-CN', {
你说得没毛病，去掉了。  35c26639a9f5d4ba34fb29f51e933f902d3216be

2024-12-26 08:08 UTC, seasonyuu commented on src-tauri/Cargo.toml
>  tauri = { version = "2.0.0-beta", features = [] }
先到 2.1.1 。这里是因为 Tauri 的主仓到 2.1.1，但是 plugin 相关的版本到了 2.2.0 ，为了避免不必要的意外，先到 2.1.1 。
42cecbfa75cdd9e5293d115c57f68a603f05f3de

2025-09-08 06:57 UTC, closed without merging